In [1]:
import pandas as pd

In [5]:
dt=pd.read_excel('Data/evade.xlsx', engine='openpyxl', index_col=0)

In [6]:
dt.head()

Refund  Marital_Status  Taxable_Income  Evade
Tid                                               
1         1               0          125000      0
2         0               1          100000      0
3         0               0           70000      0
4         1               1          120000      0
5         0               2           95000      1

In [7]:
dt.columns

Index(['Refund', 'Marital_Status', 'Taxable_Income', 'Evade'], dtype='object')

In [11]:
inputs=dt[['Refund', 'Marital_Status', 'Taxable_Income']]
outputs=dt[['Evade']]

In [13]:
from sklearn.naive_bayes import GaussianNB
import numpy as np
from sklearn.utils.validation import column_or_1d

In [14]:
NB=GaussianNB()

In [15]:
NB.fit(inputs, column_or_1d(outputs))

GaussianNB()

In [16]:
#score:
NB.score(inputs,np.array(outputs))

1.0

In [18]:
NB.classes_

array([0, 1])

In [19]:
x_test=[[0,1,12000]]
y_test=NB.predict(x_test)

In [20]:
y_test

array([0])

In [21]:
#save model
import pickle
name='NB.pkl'
with open(name, 'wb') as file:
    pickle.dump(NB, file)

In [22]:
with open(name, 'rb') as file:
    model=pickle.load(file)

In [23]:
x_now=[[1,1,13000]]
y_now=model.predict(x_now)
y_now

array([0])