In [1]:
import pandas as tespttdttttttttang

In [10]:
df=pd.read_csv('Data/titanic_csv.csv', index_col=0)

In [11]:
df.head()

pclass  survived                                             name     sex  \
1       1         1                    Allen, Miss. Elisabeth Walton  female   
2       1         1                   Allison, Master. Hudson Trevor    male   
3       1         0                     Allison, Miss. Helen Loraine  female   
4       1         0             Allison, Mr. Hudson Joshua Creighton    male   
5       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   

       age  sibsp  parch  ticket      fare    cabin embarked  \
1  29.0000      0      0   24160  211.3375       B5        S   
2   0.9167      1      2  113781  151.5500  C22 C26        S   
3   2.0000      1      2  113781  151.5500  C22 C26        S   
4  30.0000      1      2  113781  151.5500  C22 C26        S   
5  25.0000      1      2  113781  151.5500  C22 C26        S   

                         home.dest  
1                     St Louis, MO  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON  
4  Montreal, PQ / Chesterville, ON  
5  Montreal, PQ / Chesterville, ON

In [13]:
df.columns

Index(['pclass', 'survived', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket',
       'fare', 'cabin', 'embarked', 'home.dest'],
      dtype='object')

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1309 entries, 1 to 1309
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   pclass     1309 non-null   int64  
 1   survived   1309 non-null   int64  
 2   name       1309 non-null   object 
 3   sex        1309 non-null   object 
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   int64  
 6   parch      1309 non-null   int64  
 7   ticket     1309 non-null   object 
 8   fare       1308 non-null   float64
 9   cabin      295 non-null    object 
 10  embarked   1307 non-null   object 
 11  home.dest  745 non-null    object 
dtypes: float64(2), int64(4), object(6)
memory usage: 132.9+ KB


In [15]:
#filling missing values:
df=df.interpolate()

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1309 entries, 1 to 1309
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   pclass     1309 non-null   int64  
 1   survived   1309 non-null   int64  
 2   name       1309 non-null   object 
 3   sex        1309 non-null   object 
 4   age        1309 non-null   float64
 5   sibsp      1309 non-null   int64  
 6   parch      1309 non-null   int64  
 7   ticket     1309 non-null   object 
 8   fare       1309 non-null   float64
 9   cabin      295 non-null    object 
 10  embarked   1307 non-null   object 
 11  home.dest  745 non-null    object 
dtypes: float64(2), int64(4), object(6)
memory usage: 132.9+ KB


In [18]:
x=df[['pclass','sex', 'age', 'sibsp', 'parch','fare','embarked']]
y=df['survived']

In [19]:
x=pd.get_dummies(x)
x.head()

pclass      age  sibsp  parch      fare  sex_female  sex_male  embarked_C  \
1       1  29.0000      0      0  211.3375           1         0           0   
2       1   0.9167      1      2  151.5500           0         1           0   
3       1   2.0000      1      2  151.5500           1         0           0   
4       1  30.0000      1      2  151.5500           0         1           0   
5       1  25.0000      1      2  151.5500           1         0           0   

   embarked_Q  embarked_S  
1           0           1  
2           0           1  
3           0           1  
4           0           1  
5           0           1

In [22]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.2)

In [23]:
fr=RandomForestClassifier(n_estimators=100)
fr.fit(x_train, y_train)

RandomForestClassifier()

In [24]:
y_pred=fr.predict(x_test)

In [25]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred, y_test)

0.7633587786259542

In [28]:
mat=pd.DataFrame({'Actual':pd.DataFrame(y_test.values)[0].values, 'Predict':pd.DataFrame(y_pred)[0]})
mat.head()

Actual  Predict
0       0        0
1       1        1
2       0        0
3       1        0
4       0        0

In [30]:
#evaluating training score and testing score:
fr.score(x_train, y_train)

0.9904489016236867

In [31]:
fr.score(x_test, y_test) #slightly overfitting..

0.7633587786259542

## Finding important features to improve models

In [34]:
import numpy as np
x_filter=pd.Series(fr.feature_importances_, index=np.array(x.columns)).sort_values(ascending=False)
x_filter

age           0.289386
fare          0.238764
sex_female    0.151949
sex_male      0.134337
pclass        0.080853
sibsp         0.042720
parch         0.029722
embarked_C    0.015265
embarked_S    0.011412
embarked_Q    0.005592
dtype: float64

In [35]:
x_filter[x_filter>=0.05].sum()

0.8952891016111182

In [36]:
# take count for more than 80%
x_filter=x_filter[x_filter>=0.05]
x_filter

age           0.289386
fare          0.238764
sex_female    0.151949
sex_male      0.134337
pclass        0.080853
dtype: float64

In [37]:
inputs=x[['age','fare','sex_female','sex_male','pclass']]
outputs=y

In [38]:
x_train, x_test, y_train, y_test=train_test_split(inputs, outputs, test_size=0.3)

In [39]:
fr_1=RandomForestClassifier(n_estimators=100)
fr_1.fit(x_train, y_train)

RandomForestClassifier()

In [40]:
y_pred=fr_1.predict(x_test)

In [41]:
accuracy_score(y_pred, y_test) # slightly improve

0.816793893129771

In [42]:
fr_1.score(x_train, y_train)

0.9847161572052402

In [43]:
fr_1.score(x_test, y_test)

0.816793893129771

In [45]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[215,  26],
       [ 46, 106]])

## Evaluating models

In [47]:
from sklearn.metrics import classification_report, roc_auc_score, roc_curve

In [49]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.82      0.89      0.86       241
           1       0.80      0.70      0.75       152

    accuracy                           0.82       393
   macro avg       0.81      0.79      0.80       393
weighted avg       0.82      0.82      0.81       393



In [55]:
y_prob=fr_1.predict_proba(x_test)

In [56]:
y_prob=y_prob[:,1]
y_prob[:5]

array([0.26, 0.26, 0.01, 0.04, 1.  ])

In [57]:
roc_auc_score(y_test, y_prob)

0.8477014632015725

In [59]:
#make predict
fr_1.predict([[35,50,0,1,3],[23,1,1,0,2],[70,50,1,0,4]])

array([0, 1, 0])